name: .NET Core Desktop

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - uses: actions/checkout@v4

    - name: dotnet run
      run: dotnet run -c Release --project Splatoon3ics.csproj -u https://splatoon3.ink/data/schedules.json -o docs/

    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "Schedule update"
